import "virtual:svg-icons-register";
import "../scss/style.scss";
import career from "./career";
import news from "./news";
import partners from "./partners";
import ourProducts from "./ourProducts";
import subjects from "./subjects";
import intro from "./intro";
import menu from "./menu";
import smoothScrolling from "./smoothScrolling";
import geography from "./geography";
import toggleVersions from "./toggleVersions";
import modals from "./modals";
import forms from "./forms";
import ourTeam from "./ourTeam";
import values from "./values";
import aboutGallery from "./about-gallery";
import aboutIntro from "./about-intro";
import aboutHolding from "./about-holding";
import mission from "./mission";
import achievements from "./achivements";
import team from "./team";
import selects from "./selects";
import vacancies from "./vacancies";
import fileUpload from "./fileUpload";
import careerAdvantages from "./careerAdvantages";
import successStories from "./successStories";
import search from "./search";
import fancybox from "./fancybox";
import contacts from "./contacts";

document.addEventListener("DOMContentLoaded", () => {
  smoothScrolling();
  modals();
  fileUpload();
  menu();
  search();
  toggleVersions();
  intro();
  news();
  career();
  partners();
  ourProducts();
  geography();
  subjects();
  achievements();
  toggleVersions();
  forms();
  ourTeam();
  values();
  aboutIntro();
  aboutHolding();
  mission();
  aboutGallery();
  team();
  selects();
  vacancies();
  careerAdvantages();
  successStories();
  fancybox();
  contacts();
});

window.addEventListener("load", () => {
  document.body.classList.add("loaded");
});
